app = "raven-server"

[build]
  image = "markhobson/raven-server:latest"

[[services]]
  internal_port = 8080

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
